# Classes {#classes}

## Course Schedule
A full-time graduate student typically takes about 9 credits per semester. This summer you will need to register for your Fall 2021 courses. Typically first semester courses are already selected for you with flexibility in electives later on in the program. During this upcoming semester, you will want to make sure you are registered for:

- Stat 821: Statistical Methods I (3 Credits)
- Stat 882: Mathematical Statistics I (3 Credits)
- Stat 850: Statistical Computing (2 Credits)
- Stat 810: Alpha Seminar (1 Credit)

If you will have a Graduate Teaching Assistantship (GTA) you will also need to register for:

- Stat 892: TA Prep (1 Credit)

There are instances (for example if you already came in with a Master's in Statistics), where you may be able to waive some of these first semester courses and take other courses (though from my experience this is very rare). Please contact Dr. Bert Clarke or Dr. Steve Kachman for more details on this. 

## Registration
To register for classes, you can go to MYRED (https://myred.nebraska.edu/), which is a portal where you can register for classes and view your student account. I would recommend looking through this portal in order to get familiar with all of the things that can be done in here. Under the enrollment tab, click "Search for Classes". Find the classes that you want to enroll and click "Add to Cart". Once you have added all the necessary classes click on "Shopping Cart". Once in here click "Proceed to Enrollment Checkout". If you enroll in Stat 892: TA Prep, you will need a special permission code. To get that you must email Alison Reckewey in the front office. Additionally, if you are having issues enrolling in classes she is also the person you would want to contact.

Another way to register for classes is through the Enrollment Scheduler. A walkthrough on how to register this way can be found at: https://registrar.unl.edu/student/registration/tutorials/#enroll. 

The books that you will need can also be found in MYRED. Please make sure you buy these books as they will be good references your first semester and throughout your time in the program (There are pdf versions of most of these books, just know that if you decide to stay for the PhD and take the qualifying exam, you'll need a physical copy). 

## International Student Training
International graduate students for whom English is not their native language (and did not previously graduate with a degree from an university that teaches English) and who expect to receive instructional assignments must successfully complete the Institute for International Teaching Assistants. It is a requirement of your TA if you are an international student. The 2022 dates for this is August 1 to August 12, and registration must be submitted no later than June 30, 2022. Information on how to apply and what you should expect to learn in this training program can be found at: https://www.unl.edu/gradstudies/professional-development/ita 
