# University of Nebraska {#unl}

This section consists of items that you will want to take care of before classes start, and other useful information about UNL

## UNL ID Card
Your NCard is your UNL photo identification card and is used campus-wide for many purposes including identification and access to buildings. Places that your NCard will get you access to includes the department after hours and on weekends, Campus Recreation Centers, the Nebraska Unions, and Husker sporting events. Purchases can be made using your NCard and the charges will appear on your Student Accounts Consolidated Bill found on MyRed. For example, purchases made at the any of the on campus dining options can be done using your NCard. 

The Basic Steps for obtaining your NCard are as follows:

- Submit a photo of yourself and fill out the application online
- Pick up your NCard from the Ncard office (Room 121 of the Nebraska Union on City Campus). You will need to bring a state-issued ID in order to do so. There are special instructions on how to pick up your NCard when you fill out the application. I would recommend getting this done as soon as possible once you arrive to Lincoln as you don't want to be trying to get your NCard at the same time as all the undergraduates. 
- Set up NCard account: NCard needs to be activated before it can be used to make purchases. 

Link to the NCard website to fill out application and read full list of places it can be used: https://ncard.unl.edu


## Bus Pass
All students that pay student fees will receive a mobile bus pass for the academic school year. The StarTran bus service connects City, East, and the Nebraska Innovation campuses and is covered in the student fees. Instructions on how to download this mobile bus pass should be sent out in an email towards the beginning of the semester, but also can be found on the UNL parking services website (https://parking.unl.edu/bus-riders-user-guide#student-pass) for instructions. 

There are four bus routes around the campuses:

- Bus Route 22: Goes around city campus only
- Bus Route 23: Goes around east campus only
- Bus Route 24: Holdredge (Goes between east and city campus - clockwise)
- Bus Route 25: Vine (Goes between east and city campus - counterclockwise)

Route 24 and 25 runs every 10 minutes from 7am-6pm M-F and every 20 minutes from 6pm-9pm. A list of stops and the schedule can be found on the link below. Additionally, there is an on-call van service M-F for after hours. From personal experience the buses tend to not be on schedule and can get overly crowded at specific times, so when traveling between campuses make sure to take this into account.

**This past year due to COVID-19, a bus pass was not required. I'm not quite sure if that will remain true for next school year, but the university will send an email closer to the beginning of the school year with that information** 

Bus Website: https://parking.unl.edu/campus-bus-service

## Parking Pass

Due to the location of Hardin Hall (where the Statistic Offices and many of your classes will be), most students in the department do not purchase a parking pass and instead park in the neighborhoods across the street. 

However, if you do decide you would like to purchase a parking pass, more information can be found here: https://parking.unl.edu/}{Parking Pass Information

## SAS License 
SAS is a statistical software that if you are not familiar with quite yet, you soon will be as it is commonly used in your first semester of courses and throughout the program. In order to get this installed on your computer, first you must stop in and see Jules Meyers in the statistics main office (Hardin 340) in order to pay the license fee. It is $\$60$ if pay using your NCard and $65 if paying using cash or check. This can be paid using your NCard once it is activated, check, or exact cash. After this is paid, you will need to take your computer to see Steve Westerholt in 342A Hardin Hall so he can install SAS on your computer. This may take awhile so make sure that you have a couple of hours where you will not need your laptop. Make sure you bring your power cord with you as well. Additionally, I would recommend doing this the week before classes start, as Steve tends to be busy with SAS renewals the first week of class that may cause a backup. Also there has been some students using SAS onDemand, which is free for students (though as SAS is something you will be using a lot at least through your first year, it is easier to use it using the license).

Also as a heads up, SAS is easily installed on a PC, however if you have a MAC not as much. There are different options that Steve will brief you on when you give him your laptop. 

## Campus Wi-Fi
Another important thing to do when you arrive on campus is to set up your computer with the campus Wi-Fi. We usually go over this as a department before the first week of classes, however, instructions can be found at https://its.unl.edu/services/wi-fi/ on how do to do this. This needs to be done before Steve can install SAS on your computer, and he should be able to help if you are having issues connecting to the Wi-Fi network. 


## Printing 
If you have a PC, Steve Westerholt will be able to easily connect you to one of the printers within the department, which is very convenient. If you have a MAC, I'm sure this may still be able to be done, but I would talk to Steve to get more information on this.

## Student Fees

Here is a list of the Mandatory Student Fees you should be aware of as listed on the Universities Website for the 2021-2022 academic year:

- Registration Fee - $20.00 (due each semester a student registers for classes)
- Technology Fee - $11.00 per credit hour
- ID Card Fee - $20.00 (One time fee assesed when pick up first NCard)
- Library Fee - $6.25 per credit hour
- University Program/Facilities Fee - $631.00
- New International Graduate Fee - $150.00 (One-time fee due the first semester an international graduate student is enrolled)
- International Graduate Student Fee - $70.00 (for every semester after the first)
- There are also late fees for failing to pay you bill on time and if you register for classes late.

Optional Student Fees (This is updated for the 2021-2022 Academic Year):

- Health Insurance Fall - $1392.74
- Health Insurance Spring/Summer - $1930.42

Graduate students are automatically enrolled in the health insurance plan, so if you have your own health insurance you can opt out (You have until sometime in September to do this and will have to prove that you have health insurance). International students must be enrolled in university health insurance, cannot opt out most of the time for a personal insurance. Exceptions are rare and difficult to obtain. 

If you have funding from the department, check your contract for a insurance coverage. It is common that included with an assistantship, a portion of the student health insurance premium will be covered.

More information on the Student Health Insurance:
https://studentaccounts.unl.edu/student-health-insurance

Where student fee and tuition information should hopefully be updated: https://studentaccounts.unl.edu/graduate-tuition#ay_fee_block

## University Health Center
This section is more of an FYI, but UNL has a health center that offers many different services that may be of interest especially if you are not from Nebraska. For example, they offer primary care, pharmacy, dental services, immunization clinic, counseling and psychological services, and may others that are all located within a building on city campus. Some of these services are offered for free (like receiving a flu shot) and for others you either can use your student health insurance (things like check-ups would be completely covered), or if you have your own the university works with most insurance companies. More information can be found here: https://health.unl.edu

Additionally if you do not want to go to the health center, for dental services, the dental college on east campus offers dental services with one of their dental students for a significantly reduced cost. 

## East Campus

Unless you are teaching on City Campus, or taking a class out of the department, you will spend pretty much all of your time on East Campus.The University has put a lot of work into renovating parts of East Campus the last few years. Among these renovations is the East Campus Rec Center (need NCard to enter), the East Campus Union (has places to buy snacks and to study), and the Dinsdale Learning Commons (aka the library), which has a lot of places to study at. Additionally, there is an Arboretum with tables if you ever want to study outside. So don't feel like you have to spend all of your time in Hardin, and make use of some of these nice and rennovated facilities. 

