# Housing {#housing}

## Living Suggestions

Lincoln, Nebraska has a great selection of housing. Below is a list of locations and complexes current graduate students in our department have lived or currently live:

Within walking distance of the department (East Campus)

- No name: 3331 Holdrege St
    - Contact: Brian Craft at <Brian@rentbhg.com> (can also google, and things should pop up)
- 3405 Holdrege Street, Shack LLC, owned by Beth Gaylord (Very Clean apartments, 2 mins walk to the department) 
    - https://www.apartmenthomeliving.com/apartment-finder/Shacks-LLC-Lincoln-NE-68503-5917259
- There are a handful of apartments along Holdrege Street all within walking distance or easily hop on a bus directly to the department, they don’t really have names, but you can draw a polygon on this website and see what is available within this distance.
    - https://www.apartments.com/?sk=12394ce32a178ee889f5950ad651d0cb&bb=jys406n_3Kq1glU
- 35 East (WRK Real Estate)
    - https://www.thirtyfiveeast.com/

Nearby East Campus (Could walk, but might be a little longer walk)

- Square at 48 (there is a bus directly from here to the department)
    - https://www.squareat48.com/
- Ashley Square Apartments (Easy walk, but might be chilly in the winter)
    - https://www.apartmentguide.com/apartments/Nebraska/Lincoln/Ashley-Square/22090/
- Another polygon area which you could easily bus from 
    - https://www.apartments.com/?sk=1a0482a94076d43e0c11ac36d3c6fa52&bb=i98ymjn93KstyhP

Not within walking distance of the department, but nearby (East Campus)

- Chateau Development (there is a bus within walking distance of their Trailview Campus from here to the department)
    - https://www.chateaudev.com/
- Tanglewood (No bus directly to East Campus, bus goes directly to City Campus only)
    - https://www.richdale.apartments/tanglewood-apartments-1/index.aspx?utm_knock=g
- Lions Gate (No bus directly to East Campus, bus goes directly to City Campus only)
    - https://www.richdale.apartments/lionsgate-apartments/index.aspx?utm_knock=g
- The Flats at Leighton District
    - https://www.ldflats.com/
- Cheever Apartments
    - https://www.cheeverproperties.com/cheever-apartments/index.aspx
- The Fairways at Lincoln
    - https://www.hpifairwayslincoln.com/
- The 50/50 - seems to be college living not associated with the university (and seemingly nicer apartments). You'll get assigned roommates if you don't have them already. 
    - https://www.the50-50.com/
- Telegraph Distict (new and fancy, but Allo internet included in the rent)
    - https://www.telegraphdistrict.com/

Other possible companies to contact

- JTT Holdings Company
-	Rental Real Estate
-	Century Sales and Management
- WRK Real Estate (35 East close to campus and Canopy Lofts downtown)

Most students seemed to have found an apartment by just googling "apartments in Lincoln", or looking through apartment rental sites like Zillow. Many apartments have been built in recent years, so it is pretty easy to find one (according to a student, you probably don't even have to start looking until 30-60 days in advance). 

Here is the Information Page from Grad Studies about relocating to Lincoln for more helpful information: https://www.unl.edu/gradstudies/admissions/relocate

If you are interested in finding a roommate:

- Reach out to one of the Stat GSA officers and we will send out a message to see if any current students are looking for a roommate. Not gauranteed, but we will do our best to help connect you.
- University of Nebraska Facebook Page
- UNL CSSA (Chinese Student and Scholar Association) - has page on UNL website and a Facebook page.
- If you are from India, the Indian Student Association (who has a facebook page) can help potentially connect you with a roommate and potential places to live. 
- Also, there's been multiple instances of people starting off by living alone, then moving in with friends they make in the department. So that may be an option later.  


## Furniture

If you are in need of some new/used furniture, here are some recommendations:

- Facebook marketplace
- OfferUp is a good app to find used furniture.
- UNL CSSA Facebook Page
- UNL Buy and Sell Facebook Page
- Goodwill
- Ernie's in Ceresco
- Craigslist
- Walmart
- Target
- Furniture Row
- Amazon: will probably have to do your own assembling, but a good option if you don't have a car
- Nebraska Furniture Mart: located in Omaha and is a bit more on the expensive side compared to these other places, but it's really nice new furniture. It is a set of multiple buildings, and there is a clearance building called Mrs. B's with discounted furniture. In most cases, for an additional fee, they can ship it to Lincoln and bring it into your housing for you. 
$\\$

## Grocery Stores

There a quite a few different grocery stores around Lincoln, here is a list of popular grocers used by students in this department:

- Hyvee
- Walmart
- Sam's Club
- Supersaver
- Trader Joe's in South Lincoln
- Aldi's
- Target
- Natural Grocers
- Costco
- Suji's Indian Grocery
- Guerrero's Market on S 11th St (Mexican Grocery Store)
- Little Saigon Oriental Market (Asian)
- Oriental Market (Asian)
- Additionally in Omaha there is a Bangladeshi fish market and a good Indian grocery store


