# Statistics Graduate Student Association (Stat GSA) {#statGSA}

## Events

The Stat GSA has a couple of different events throughout the year as a way to get to know your fellow students and hopefully have some fun!:

- Monthly Happy Hours
- Cultural Potluck: Once a semester we have a potluck where students bring food from their native country to share with department. There is a wonderful variety of food and there are quite a few good cooks within the department!
- Study Breaks: About once a month, we have a study break where a couple of students are in charge of bringing snacks to share.
- Spring Event: Typically we have a fun event in the spring as a celebration of the end of the year. In years past we have typically gone bowling, though this last spring we did go to Top Golf in Omaha!

More information on dates and location of these will be sent to your emails, so be sure to check those!

Additionally, we ask that each semester students pay $5.00 in due money to go towards buying drinks for the potluck and to help pay for the Spring Event. 



## Social Media

Follow us on Twitter `@unl_statistics` to stay up-to-date with what is going on within the department and the university. 
