# Advice from Current Graduate Students {#advice}

What is one good tip you were given prior to Grad School?

- "Relax the summer before"
- "Don't stress about results, just enjoy the experience"
- "You will definitely be overwhelmed considering that it is a big leap from the undergrad studies. But everything will be fine"
- "MEAL PREPPING!"
- "Stay connected with others and the department"
- "Have a great balance between work and life. That means that no one should study ALL the time. Finding a hobby or hobbies will help with the stress of graduate school."
- "You might need to re-learn how to study/do homework. It's a lot different from undergraduate!"
- "Don't take everything too seriously"
- "Make sure to make time for fun"
- "All the students are in this together. Work together. Ask each other questions. Help each other."
- "There will come a time in class where you will have no clue what is going on. Don't panic, you are probably not the only one. Don't be afraid to ask for help from your classmates or professors."
- "Make sure to allocate proper time for sleep (ie. choose sleep over cramming)"
- "Have a personal life. It's healthy to have a balance!"
- "Grad school is a team sport. Work together, learn more."
- "Treat it like a job, go into the office during the workday. Just be around and you will make connections."
- "Form a habit to search and read related paper by yourself"
- "Ask people to hang out. It's easy to be lonely."

What is something you wish you had known before moving to Lincoln and beginning graduate school?

- "Should keep very organized notes that I can refer to later in the semester"
- "Managing a balanced life"
- "Public transport is not great, it would be useful to find housing near bus routes or have your own car."
- "Lot of outdoor activities conducted by UNL outdoor adventure center, great way to make new friends who enjoy doing the same things as you. Beer tours at Zipline - good way of making friends outside of your academic circle. Lot of events are organized by different international students organizations - Malaysia night, India night, good way to meet new people."
- "It's very important to form a cohort, even if that's not the people starting at the same time as you. Form study groups, find people you can ask questions or get advice from. Grad school is a collaborative experience!"
- "know and constantly communicate with everyone in your cohort. Makes everything easier"
- "Making new friends takes effort. Work hard to deepen friendships. Also, they don't plow residential roads."
- "Enjoy this time to learn and meet new friends. Many people will be your future colleagues and those who will remain in your life for the extended future."
- "Get creative with your coursework and projects. Take classes in the computer science, or economics department. Don't just stick with the normal classes. Go above and beyond."
- "This experience is what you make of it. If you don't put in the work to get to know your fellow students and faculty, and attend events hosted by either the gsa or department, the experience probably won't be as fun. It's also a chance to network with people who will be your peers."
- "Make time to prioritize fun activities during grad school. Lincoln is a nice sized town with a lot to do - seek it out!"
- "Bring more thick clothes like down jacket, winter in Lincoln can be very cold"
- "The wind is strong"
- "I wish I had known that working with others would become commonplace. It's honestly been a difficult transition for me. Also, Lincoln can be difficult to find stuff to do at times, in my opinion."
- "Grades are irrelevant (learning is more important), it's a better use of time to work on more projects than spend time on improving grades."
- "Advisor shop - go talk to a handful of professors about their research and potential projects before selecting an advisor. Find someone who fits both your interests and personality."
- "Introduce yourself to people and make friends. Everyone is very friendly."
- "If you are coming from Asia, buy Casella and Berger at home before coming to the US. Wayyy cheaper. "
- "Join the American Statistical Association and find the community threads that are of interest to you. This is how you will make a lot of connections."


This was touched upon above, but no matter if you plan on just getting a Master's or getting the PhD, it is important to find an advisor. This isn't something you need to do right away, but I would try and find one by the end of your first year, as this will help make sure you are doing everything you need to do in order to graduate and be successful after graduation. So during your first semester, I would try and talk to a bunch of different professors about their research interests so you can pinpoint one that has research you are interested in and you can work with well. Sounds scary, but will be very helpful to do in the long run. 